<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="80" result="Failed" total="19" passed="0" failed="19" inconclusive="0" skipped="0" asserts="0" engine-version="3.9.0.0" clr-version="4.0.30319.42000" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:43Z" duration="1.055036">
  <command-line><![CDATA[nunit3-console.exe  E:\Automation\Autoscoring_Automation\Automated.Tests\bin\Debug\Automated.Tests.dll --where "cat == SmokeTests" --labels=All --out=TestResult.txt --work=E:\Automation\Autoscoring_Automation\Test.Automation.Output\Reports\2018-11-05-04-36PM]]></command-line>
  <filter>
    <cat>SmokeTests</cat>
  </filter>
  <test-suite type="Assembly" id="0-1089" name="Automated.Tests.dll" fullname="Automated.Tests.dll" runstate="Runnable" testcasecount="80" result="Failed" site="Child" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:43Z" duration="0.494071" total="19" passed="0" failed="19" warnings="0" inconclusive="0" skipped="0" asserts="0">
    <environment framework-version="3.11.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.17134.0" platform="Win32NT" cwd="E:\Automation\Autoscoring_Automation\packages\NUnit.ConsoleRunner.3.9.0\tools" machine-name="DSATY-10-10170" user="doaa.saty" user-domain="ITWORX" culture="en-US" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="DisposeRunners" value="True" />
      <setting name="WorkDirectory" value="E:\Automation\Autoscoring_Automation\Test.Automation.Output\Reports\2018-11-05-04-36PM" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.5.2" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="4" />
    </settings>
    <properties>
      <property name="_PID" value="11336" />
      <property name="_APPDOMAIN" value="domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1090" name="Automated" fullname="Automated" runstate="Runnable" testcasecount="80" result="Failed" site="Child" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:43Z" duration="0.477038" total="19" passed="0" failed="19" warnings="0" inconclusive="0" skipped="0" asserts="0">
      <properties />
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="0-1091" name="Tests" fullname="Automated.Tests" runstate="Runnable" testcasecount="80" result="Failed" site="Child" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:43Z" duration="0.474422" total="19" passed="0" failed="19" warnings="0" inconclusive="0" skipped="0" asserts="0">
        <properties />
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestSuite" id="0-1092" name="Scripts" fullname="Automated.Tests.Scripts" runstate="Runnable" testcasecount="80" result="Failed" site="Child" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:43Z" duration="0.474413" total="19" passed="0" failed="19" warnings="0" inconclusive="0" skipped="0" asserts="0">
          <properties />
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-suite type="TestSuite" id="0-1096" name="Login" fullname="Automated.Tests.Scripts.Login" runstate="Runnable" testcasecount="50" result="Failed" site="Child" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:43Z" duration="0.474398" total="19" passed="0" failed="19" warnings="0" inconclusive="0" skipped="0" asserts="0">
            <properties />
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
            </failure>
            <test-suite type="TestFixture" id="0-1048" name="SmokeTests" fullname="Automated.Tests.Scripts.Login.SmokeTests" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" testcasecount="19" result="Failed" site="Child" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:43Z" duration="0.470857" total="19" passed="0" failed="19" warnings="0" inconclusive="0" skipped="0" asserts="0">
              <properties />
              <failure>
                <message><![CDATA[One or more child tests had errors]]></message>
              </failure>
              <test-case id="0-1049" name="LoginToApplication" fullname="Automated.Tests.Scripts.Login.SmokeTests.LoginToApplication" methodname="LoginToApplication" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="1465519751" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.307890" asserts="0">
                <properties>
                  <property name="Order" value="1" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1050" name="SearchByExperimentName" fullname="Automated.Tests.Scripts.Login.SmokeTests.SearchByExperimentName" methodname="SearchByExperimentName" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="690785256" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.023843" asserts="0">
                <properties>
                  <property name="Order" value="2" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1051" name="ValidatePagingComponents" fullname="Automated.Tests.Scripts.Login.SmokeTests.ValidatePagingComponents" methodname="ValidatePagingComponents" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="368149268" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.008112" asserts="0">
                <properties>
                  <property name="Order" value="3" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1052" name="ValidateSearchByMarkerName" fullname="Automated.Tests.Scripts.Login.SmokeTests.ValidateSearchByMarkerName" methodname="ValidateSearchByMarkerName" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="1460486510" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.007499" asserts="0">
                <properties>
                  <property name="Order" value="4" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1053" name="SearchByMarkerNameWithExpandingRows" fullname="Automated.Tests.Scripts.Login.SmokeTests.SearchByMarkerNameWithExpandingRows" methodname="SearchByMarkerNameWithExpandingRows" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="597137855" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.007994" asserts="0">
                <properties>
                  <property name="Order" value="5" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1054" name="ValidateReadingScorePreviewWindowIsDisplayed" fullname="Automated.Tests.Scripts.Login.SmokeTests.ValidateReadingScorePreviewWindowIsDisplayed" methodname="ValidateReadingScorePreviewWindowIsDisplayed" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="1279754103" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.007613" asserts="0">
                <properties>
                  <property name="Order" value="6" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1055" name="ValidateNavigationInReadingScoreWindow" fullname="Automated.Tests.Scripts.Login.SmokeTests.ValidateNavigationInReadingScoreWindow" methodname="ValidateNavigationInReadingScoreWindow" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="725032518" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.007407" asserts="0">
                <properties>
                  <property name="Order" value="7" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1056" name="ValidateTheDownloadReadingBtnIsWorking" fullname="Automated.Tests.Scripts.Login.SmokeTests.ValidateTheDownloadReadingBtnIsWorking" methodname="ValidateTheDownloadReadingBtnIsWorking" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="1506899801" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.007463" asserts="0">
                <properties>
                  <property name="Order" value="8" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1057" name="ValidateTheTaskDetailsWindowIsShowingUp" fullname="Automated.Tests.Scripts.Login.SmokeTests.ValidateTheTaskDetailsWindowIsShowingUp" methodname="ValidateTheTaskDetailsWindowIsShowingUp" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="63844537" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.010016" asserts="0">
                <properties>
                  <property name="Order" value="9" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1058" name="ValidateTheTableViewTabIsLoading" fullname="Automated.Tests.Scripts.Login.SmokeTests.ValidateTheTableViewTabIsLoading" methodname="ValidateTheTableViewTabIsLoading" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="2132802778" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.007458" asserts="0">
                <properties>
                  <property name="Order" value="10" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1059" name="ValidateThePlateViewTabIsLoading" fullname="Automated.Tests.Scripts.Login.SmokeTests.ValidateThePlateViewTabIsLoading" methodname="ValidateThePlateViewTabIsLoading" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="1235785643" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.007285" asserts="0">
                <properties>
                  <property name="Order" value="11" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1060" name="ValidateThePlotViewTabIsLoading" fullname="Automated.Tests.Scripts.Login.SmokeTests.ValidateThePlotViewTabIsLoading" methodname="ValidateThePlotViewTabIsLoading" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="1646231976" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.007269" asserts="0">
                <properties>
                  <property name="Order" value="12" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1061" name="ChangeScreenModeToEnquiry" fullname="Automated.Tests.Scripts.Login.SmokeTests.ChangeScreenModeToEnquiry" methodname="ChangeScreenModeToEnquiry" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="1528771088" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:42Z" duration="0.007103" asserts="0">
                <properties>
                  <property name="Order" value="13" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1062" name="ChangeScreenModeToWork" fullname="Automated.Tests.Scripts.Login.SmokeTests.ChangeScreenModeToWork" methodname="ChangeScreenModeToWork" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="941662122" result="Failed" label="Error" start-time="2018-11-05 14:36:42Z" end-time="2018-11-05 14:36:43Z" duration="0.007581" asserts="0">
                <properties>
                  <property name="Order" value="14" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1063" name="ValidateTheFourTechnologiesArePopulatedInTheDDL" fullname="Automated.Tests.Scripts.Login.SmokeTests.ValidateTheFourTechnologiesArePopulatedInTheDDL" methodname="ValidateTheFourTechnologiesArePopulatedInTheDDL" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="24370453" result="Failed" label="Error" start-time="2018-11-05 14:36:43Z" end-time="2018-11-05 14:36:43Z" duration="0.007288" asserts="0">
                <properties>
                  <property name="Order" value="15" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1064" name="VerifythatNexarHasNoFileTypeDdl" fullname="Automated.Tests.Scripts.Login.SmokeTests.VerifythatNexarHasNoFileTypeDdl" methodname="VerifythatNexarHasNoFileTypeDdl" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="1196507748" result="Failed" label="Error" start-time="2018-11-05 14:36:43Z" end-time="2018-11-05 14:36:43Z" duration="0.008509" asserts="0">
                <properties>
                  <property name="Order" value="16" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1065" name="VerifyThatTaqmanHasCorrectFileTypes" fullname="Automated.Tests.Scripts.Login.SmokeTests.VerifyThatTaqmanHasCorrectFileTypes" methodname="VerifyThatTaqmanHasCorrectFileTypes" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="2054382103" result="Failed" label="Error" start-time="2018-11-05 14:36:43Z" end-time="2018-11-05 14:36:43Z" duration="0.007491" asserts="0">
                <properties>
                  <property name="Order" value="17" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1066" name="ValidateTheDownloadTaskFileLinkIsWorking" fullname="Automated.Tests.Scripts.Login.SmokeTests.ValidateTheDownloadTaskFileLinkIsWorking" methodname="ValidateTheDownloadTaskFileLinkIsWorking" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="1701665230" result="Failed" label="Error" start-time="2018-11-05 14:36:43Z" end-time="2018-11-05 14:36:43Z" duration="0.007008" asserts="0">
                <properties>
                  <property name="Order" value="18" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
              <test-case id="0-1067" name="ValidateViewReportLinkIsWorking" fullname="Automated.Tests.Scripts.Login.SmokeTests.ValidateViewReportLinkIsWorking" methodname="ValidateViewReportLinkIsWorking" classname="Automated.Tests.Scripts.Login.SmokeTests" runstate="Runnable" seed="1818693259" result="Failed" label="Error" start-time="2018-11-05 14:36:43Z" end-time="2018-11-05 14:36:43Z" duration="0.007072" asserts="0">
                <properties>
                  <property name="Order" value="19" />
                  <property name="Category" value="SmokeTests" />
                  <property name="Retry" value="3" />
                </properties>
                <failure>
                  <message><![CDATA[System.IO.IOException : The process cannot access the file 'E:\Automation\Autoscoring_Automation\Automated.Tests\Data\AutoscoringTestData.xlsx' because it is being used by another process.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                  <stack-trace><![CDATA[   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.ParseExcelTestData(Boolean useHeaderRow, Int32 startingRowIndex, Int32 startingColumnIndex)
   at Automated.Utilities.Utilities.Parsers.ExcelDataParser.Init(String testDataFilePath)
   at Automated.Tests.TestConfigs.Init(String automationConf) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestConfigs.cs:line 141
   at Automated.Tests.TestCommons.TestCommons_Setup(String automationConfigs) in E:\Automation\Autoscoring_Automation\Automated.Tests\TestCommons.cs:line 26
   at Automated.Tests.TestMain.SetupTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 41
--TearDown
   at Automated.Utilities.Reporting.TestReport.GenerateReport()
   at Automated.Tests.TestMain.TeardownTest() in E:\Automation\Autoscoring_Automation\Automated.Tests\TestMain.cs:line 57]]></stack-trace>
                </failure>
              </test-case>
            </test-suite>
          </test-suite>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>